### ISSUE TITLE
layers/meta-openembedded/meta-oe/recipes-benchmark/glmark2/glmark2_git.bb:do_configure) failed with exit code '1'

### ISSUE THREAD

**Issue by pywtk** [STMicroelectronics/meta-st-stm32mpu-app-aws#5]
```
| Traceback (most recent call last):
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Node.py", line 297, in ant_iter
|     raise StopIteration
| StopIteration
| 
| The above exception was the direct cause of the following exception:
| 
| Traceback (most recent call last):
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Scripting.py", line 120, in waf_entry_point
|     run_commands()
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Scripting.py", line 177, in run_commands
|     parse_options()
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Scripting.py", line 150, in parse_options
|     Context.create_context('options').execute()
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Options.py", line 145, in execute
|     super(OptionsContext,self).execute()
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Context.py", line 88, in execute
|     self.recurse([os.path.dirname(g_module.root_path)])
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Context.py", line 129, in recurse
|     user_function(self)
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/wscript", line 37, in options
|     opt.load('compiler_c')
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Context.py", line 85, in load
|     fun(self)
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Tools/compiler_c.py", line 40, in options
|     opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Context.py", line 315, in load_special_tools
|     lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Node.py", line 346, in ant_glob
|     ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
|   File "/tmp/ggdnfll/build-openstlinuxweston-stm32mp1-demo-aws/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/glmark2/20191226+AUTOINC+5e0e448ca2-r0/git/waflib/Node.py", line 346, in <listcomp>
|     ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
| RuntimeError: generator raised StopIteration
| WARNING: exit code 2 from a shell command.
```
looks like this was fixed here?

https://github.com/waf-project/waf/commit/facdc0b173d933073832c768ec1917c553cb369c

**Comment by tganeshg** [comment]
Getting same error.., any one can help ?
